name: Deploy Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --name MyDeployment \
          --resource-group MyResourceGroup \
          --template-file azuredeploy.bicep \
          --parameters adminUsername=adminUser adminPassword=adminPassword vmName=myVMName

    - name: Show Outputs
      run: |
        az deployment group show \
          --name MyDeployment \
          --resource-group MyResourceGroup \
          --query properties.outputs
