name: Deploy Azure VM

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
     name: staging.azure
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    # storage account deploy
    # - name: Deploy Bicep Template
    #   run: |
    #     az deployment group create \
    #       --name MyDeployment \
    #       --resource-group ${{ secrets.AZURE_RG }} \
    #       --template-file storage_deploy.bicep \

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --name MyDeployment \
          --resource-group ${{ secrets.AZURE_RG }} \
          --template-file vm_deploy.bicep \
          --parameters adminUsername=vaibbavisk

    # - name: Show Outputs
    #   run: |
    #     az deployment group show \
    #       --name MyDeployment \
    #       --resource-group MyResourceGroup \
    #       --query properties.outputs
