name: Deploy Azure VM

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
     name: staging.azure
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

# client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#           resource-group-name: ${{ secrets.AZURE_RG }}
#           admin-username: ${{ secrets.ADMIN_USERNAME }}
#           admin-password: ${{ secrets.ADMIN_PASSWORD }}
    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --name MyDeployment \
          --resource-group MyResourceGroup \
          --template-file vm_deploy.bicep \
          --parameters adminUsername=vaibbavisk secureAdminPassword=Testing1234 vmName=newVmVsk

    - name: Show Outputs
      run: |
        az deployment group show \
          --name MyDeployment \
          --resource-group MyResourceGroup \
          --query properties.outputs
