name: Deploy Azure Storage Account

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
     name: staging.azure
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false
    - name: name generator
      uses: TGPSKI/name-generator-node-action@v2
      id: generator
      with:
        separator: ''
        length: '4'
        style: 'lowerCase'

    - name: test generator output
      run: echo "latest,${{ steps.generator.outputs.name }}"
    
    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --name MyDeployment \
          --resource-group ${{ secrets.AZURE_RG }} \
          --template-file storage_deploy.bicep \
          --parameters storageAccountName=${{ steps.generator.outputs.name }}
