name: Deploy Azure Storage Account

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: az cli login
      uses: azure/login@hf_447_release
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    
    - name: 'Install azd'
      uses: Azure/setup-azd@v0.1.0
  
    - name: 'Install Nodejs'
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Az powershell
      uses: azure/powershell@v2
      with:
        inlineScript: |
          mkdir azd-repo
          cd azd-repo
          azd init -t Azure-Samples/azure-search-openai-demo --no-prompt
          azd env new ${{ vars.AZURE_ENV_NAME }}
          azd env set AZURE_ENV_NAME ${{ vars.AZURE_ENV_NAME }}
          azd env set AZURE_LOCATION  ${{ vars.AZURE_LOCATION }}
          azd env set AZURE_OPENAI_LOCATION ${{ vars.AZURE_OPENAI_LOCATION }}
          azd env set AZURE_SUBSCRIPTION_ID ${{ vars.AZURE_SUBSCRIPTION_ID }}
          azd env set AZURE_PRINCIPAL_ID ${{ secrets.AZURE_APP_ID }}
          azd env set AZURE_APP_NAME ${{ secrets.AZURE_APP_NAME }}
          azd pipeline config --auth-type federated --environment ${{ vars.AZURE_ENV_NAME }} --provider github
        azPSVersion: "latest"
    # - name: Deploy Bicep Template
    #   run: |
    #     echo ${{ secrets.AZURE_APP_NAME }}
    #     az deployment group create \
    #       --name MyDeployment \
    #       --resource-group ${{ vars.AZURE_RG }} \
    #       --template-file sql_deploy.bicep \
    #       --parameters principal_id=${{ secrets.AZURE_APP_ID }} tenant_id=${{ secrets.AZURE_TENANT_ID }} principal_name=${{ secrets.AZURE_APP_NAME }}
