name: Deploy OPEN AI 

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
     name: staging.azure
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Fetch JSON file from remote repository
      shell: bash
      run: |
        json_url="https://raw.githubusercontent.com/Azure-Samples/azure-search-openai-demo/main/infra/main.bicep"
        curl -sSLO $json_url

    # - name: Print parameter value
    #   shell: bash
    #   run: |
    #     json_file="main.bicep"
    #     # vm name
    #     # virtual_machine_name=".parameters.virtualMachineName.value"
    #     result=$(jq -r "$virtual_machine_name" "$json_file")
    #     echo "Virtual Machine Properties"
    #     echo "Name: $result"
    
    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --name MyDeployment \
          --resource-group ${{ secrets.AZURE_RG }} \
          --template-file https://raw.githubusercontent.com/Azure-Samples/azure-search-openai-demo/main/infra/main.bicep
          --parameters https://raw.githubusercontent.com/Azure-Samples/azure-search-openai-demo/main/infra/main.parameters.json
