on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:
  
  permissions:
    id-token: write
    contents: read
  jobs:
    example_job:
      runs-on: ubuntu-latest
      name: Job to run custom action
      environment:
       name: staging.azure
      steps:
        # To use this repository's private action,
        # you must check out the repository
        - name: Checkout
          uses: actions/checkout@v4
        - name: Deploy word press to azure app service
          uses: ./ # Uses an action in the root directory
          id: deploy
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resource-group-name: ${{ secrets.AZURE_RG }}
            admin-username: ${{ secrets.ADMIN_USERNAME }}
            admin-password: ${{ secrets.ADMIN_PASSWORD }}
            template: https://raw.githubusercontent.com/Azure-Samples/azure-search-openai-demo/main/infra/main.bicep
            parameters: https://raw.githubusercontent.com/Azure-Samples/azure-search-openai-demo/main/infra/main.parameters.json
            


  
  